### ISSUE TITLE
gravatar.jpg file hard coded in details page

### ISSUE THREAD

**Issue by pol76** [GeoDirectory/supreme-directory#25]
For some reason the file gravater.jpg has been hard coded in supreme details page:

`$entry_author = '<img src="'.get_stylesheet_directory_uri() . "/images/gravatar.jpg".'"  height="100" width="100">';
`
Please correct it and make it use the avatar selected by the user in settings > discussion.

See: https://wpgeodirectory.com/support/topic/user-avatars-changed-with-update/#post-376751

Thank you,

**Comment by kprajapatii** [comment]
Fixed & updated

**Comment by Stiofan** [comment]
This is deliberate but someone change the image, if the listing is not claimed then we hardcode a blank user image instead of the admin gravatar.
